### ISSUE TITLE
No date or datetime column found.

### ISSUE THREAD

**Issue by Maryoda2** [business-science/anomalize#17]
Hi ! I'm still in trouble, trying to anomalize a dataset called aqw2 and it doesn't work, this is what I get 

**Error in value[[3L]](cond) : 
  Error in prep_tbl_time(): No date or datetime column found.**

Here is the dataset
[aqw2.txt](https://github.com/business-science/anomalize/files/2197383/aqw2.txt)

Really need it's an important project, thanks so much !

**Comment by tarunparmar** [comment]
Hi,

I am having similar issue, may date column has time data and the function doesnt seem to recognize that. Were you normalizing your data from time granularity to Dates ? Or were you able to run it as it is? 
Please share. Thanks.

Tarun
