### ISSUE TITLE
Evaluation error: Only year, quarter, ...

### ISSUE THREAD

**Issue by kempspo** [business-science/anomalize#24]
I'm getting this error.

Error in mutate_impl(.data, dots) : 
  Evaluation error: Only year, quarter, month, week, and day periods are allowed for an index of class Date.

I checked the class for my date column and it returns "Date" similar to that of the date column in the example data set. An example of what's in the date column is 2014-12-04

This is the script that I run:
`
twitter.df %>%
time_decompose(count, method = "twitter", trend = "2 months") %>%
anomalize(remainder, method = "gesd") %>%
time_recompose() %>% 
plot_anomalies(time_recomposed = TRUE) 
`
I can't seem to figure out the problem with it. I've tried updating the packages and reloading them.

**Comment by pedropenzuti** [comment]
Could we get an update on this? Facing the same error.

**Comment by mdancho84** [comment]
Please provide a reproducible example.

**Comment by pedropenzuti** [comment]
Ended up finding a solution through the `tidyquant` package.
The problem arises because the columns are not periods. We can fix that by doing:

```
tq_transmute(
count, # or whatever variable you want
mutate_fun = to.period,
period = "day" # or whatever period you want)
```
It should work after that.

**Comment by mdancho84** [comment]
OK, I'm going to close since it appears not to be an issue with the package.
