### ISSUE TITLE
timetk Dependency Failing 

### ISSUE THREAD

**Issue by Miranda-Saari-Bose** [business-science/anomalize#59]
I have been working with this package for over a year now and just went to run the code again which includes the line
`install.packages("anomalize")`
At the very end of the installation returns I get

> Error: package or namespace load failed for ‘timetk’:
>  object 'required_pkgs' not found whilst loading namespace 'timetk'
> Error: loading failed
> Execution halted
> ERROR: loading failed
> * removing ‘/databricks/spark/R/lib/timetk’
> ERROR: dependency ‘timetk’ is not available for package ‘sweep’
> * removing ‘/databricks/spark/R/lib/sweep’
> ERROR: dependencies ‘timetk’, ‘sweep’ are not available for package ‘anomalize’
> * removing ‘/databricks/spark/R/lib/anomalize’
> 
> The downloaded source packages are in
> 	‘/tmp/Rtmprfwu3X/downloaded_packages’

which looks like some of the package dependencies are failing. So when I try to run 
`library(anomalize)` it fails as well.

Any idea what changed?

**Comment by mdancho84** [comment]
Please update recipes package.

**Comment by Miranda-Saari-Bose** [comment]
I ran `update.packages("recipes")` and it didn't seem to change anything

**Comment by mdancho84** [comment]
Looks awfully similar to this: https://github.com/business-science/timetk/issues/71

**Comment by mdancho84** [comment]
Make sure all of your R packages are updated. That should solve.

**Comment by Miranda-Saari-Bose** [comment]
looks like that did the trick, thanks @mdancho84!
