### ISSUE TITLE
anomalize will not load in visual studio code (VSCode) 

### ISSUE THREAD

**Issue by lepromatous** [business-science/anomalize#67]
library(anomalize) fails load with the following error:

Error: package or namespace load failed for ‘anomalize’:
 .onAttach failed in attachNamespace() for 'anomalize', details:
  call: rstudioapi::getThemeInfo()
  error: This {rstudioapi} function is not currently implemented for VSCode.

I see a lot of other rstudioapi issues with VSCode but it would be nice to at least be able to load the library sans the thematic elements if possible.

**Comment by mdancho84** [comment]
This should be fixed. Got rid of the onload. Make sure to use version 0.2.3.
