### ISSUE TITLE
Problem installing package "anomalize"

### ISSUE THREAD

**Issue by tinafreyburg** [business-science/anomalize#68]
Hi. 

The package ‘anomalize’ was removed from the CRAN repository ([https://cran.r-project.org/web/packages/anomalize/index.html]. 
We now seek to install it via github: 
```
devtools::install_github("business-science/anomalize")
install.packages("anomalize")
```
After agreeing to (a) update and (b) install from sources the packages which need compilation, we get the following error message:
`ERROR: dependencies ‘timetk’, ‘sweep’ are not available for package ‘anomalize’`

We then do the same for ‘timetk’ and for ‘sweep’, that is, e.g.
```
devtools::install_github("business-science/timetk")
install.packages("timetk")
```
However, again, after agreeing to (a) update and (b) install from sources the packages which need compilation, we get the following error message:
`ERROR: dependencies ‘forecast’, ‘tsfeatures’ are not available for package ‘timetk’`

If we then start with the first and call:
`install.packages("forecast")`
we get: 
`ERROR: dependencies ‘fracdiff’, ‘tseries’, ‘urca’ are not available for package ‘forecast’`

... and so it goes on. 

It would be fantastic if you helped us to install the package 'anomalize'. Thank you so much! 

PS: In our team, we use both MacBook and Windows computers.

**Comment by mdancho84** [comment]
Not sure. I'd try installing timetk first. It's on CRAN. 

The anomalize R package is not back on CRAN yet. I anticipate next week.

**Comment by tinafreyburg** [comment]
Thanks so much. Fingers crossed that the anomalize package will be back on CRAN very soon.

**Comment by sssiv93** [comment]
Hi @mdancho84,

Are the anomalize and sweep packages likely to be back on CRAN? If so, are you able to provide an ETA? Thank you.

**Comment by mabuimo** [comment]
The package is archived in CRAN as the sweep package dependency was archived as well
https://cran.r-project.org/package=anomalize

**Comment by mabuimo** [comment]
Also, bear in mind that installing using devtools doesn't work
`> devtools::install_github("business-science/anomalize")
Downloading GitHub repo business-science/anomalize@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  cannot open URL 'https://api.github.com/repos/business-science/anomalize/tarball/HEAD'`

**Comment by tinafreyburg** [comment]
> Not sure. I'd try installing timetk first. It's on CRAN.
> 
> The anomalize R package is not back on CRAN yet. I anticipate next week.

Hi @mdancho84, any news on this? Would be fantastic! Thanks, Tina

**Comment by srihari0606** [comment]
> 

Any news ? Is this library available on CRAN ?

**Comment by amutharun** [comment]
Hi @mdancho84 ... we have used anomalize for an AI solution and the production jobs are failing because of the CRAN unavailability. I can see that many are eagerly waiting for anomalize and sweep on CRAN. Can you please throw some light on when will it be back ?

**Comment by amanpandeynovartis** [comment]
Hello @mdancho84 , one of my projects makes use of the anomalize library and now it has become unavailable on CRAN. Please let us know when is it going to be available again, or if there is any other solution for the same. Thanks!

**Comment by mdancho84** [comment]
Use the GitHub version until I get it back on CRAN. Is a low priority for me at the moment.

**Comment by tinafreyburg** [comment]
Hello. Has any of you successfully installed the anomalize package via github? If so, I would be most grateful if you shared your magic code here. Thank you so much! Best, Tina

**Comment by ljkmail** [comment]
devtools::install_github("business-science/sweep")
devtools::install_github("business-science/anomalize")

**Comment by DiabbZegpi** [comment]
The error perseveres:

´´´ r
> devtools::install_github("business-science/anomalize")
Downloading GitHub repo business-science/anomalize@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/business-science/anomalize/tarball/HEAD' failed
´´´

**Comment by mdancho84** [comment]
`sweep` is now back on cran. I will begin working on `anomalize` soon.

**Comment by mdancho84** [comment]
Sorry lost sight of this. It's on CRAN now.
