### ISSUE TITLE
Error: `var` must evaluate to a single number or a column name, not a list

### ISSUE THREAD

**Issue by sreetamadas** [business-science/anomalize#8]
Hi,
I get the following error message when I execute the time_decompose part of the code (I am showing with only the first step; adding all steps as on  (http://www.business-science.io/code-tools/2018/04/08/introducing-anomalize.html) makes no difference) :
> t %>%
>      time_decompose(t)     #%>%   # , method = "stl", frequency = "auto", trend = "auto", message = TRUE
>
>    Converting from tbl_df to tbl_time.
>   Auto-index message: index = dateTime
>  frequency = 288 minutes
>  trend = 2880 minutes
>  Error: `var` must evaluate to a single number or a column name, not a list

I am unable to attach sample data file - so showing the first few rows from R terminal.

> >t
> A tibble: 2,304 x 2
>   dateTime             temp
>   <dttm>              <dbl>
> 1 2018-02-08 00:00:00 -11.9
> 2 2018-02-08 00:05:00 -11.9
> 3 2018-02-08 00:10:00 -11.9
> 4 2018-02-08 00:15:00 -11.9
> 5 2018-02-08 00:20:00 -11.9
> 6 2018-02-08 00:25:00 -11.9
> 7 2018-02-08 00:30:00 -11.9
> 8 2018-02-08 00:35:00 -11.9
> 9 2018-02-08 00:40:00 -11.9
>10 2018-02-08 00:45:00 -11.9
> ... with 2,294 more rows

Kindly suggest how to proceed.

**Comment by mdancho84** [comment]
You need to pass time_decompose() a column name. You are passing it a the data name and not the column name which should likely be temp in your case.

**Comment by sreetamadas** [comment]
Hi Matt, that worked. Thanks a lot.
