### ISSUE TITLE
Error in FUN(X[[i]], ...) : object '.group' not found

### ISSUE THREAD

**Issue by THE-R4U** [business-science/anomalize#9]
How can I fix it?

**Comment by mdancho84** [comment]
Try installing the development version with devtools::install_github(“business-science/anomalize”). I believe this issue was fixed already.

**Comment by tejaslodaya** [comment]
Same as #2

**Comment by mdancho84** [comment]
closed

**Comment by THE-R4U** [comment]
It's working well. Many thanks! :)
